-- ============================================================================
-- AskBase 全量建表脚本（docker-entrypoint-initdb.d 仅在空数据目录执行一次）
-- 表间引用不在库上加 FOREIGN KEY，由业务层校验
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS vector;

-- 英文按完整单词建立词元；中文同时生成单字和相邻双字词元。
CREATE OR REPLACE FUNCTION askbase_search_tokens(input TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $$
DECLARE
    source TEXT := lower(COALESCE(input, ''));
    tokens TEXT[] := ARRAY[]::TEXT[];
    ascii_token TEXT := '';
    previous_cjk TEXT := '';
    ch TEXT;
    codepoint INTEGER;
    i INTEGER;
BEGIN
    FOR i IN 1..char_length(source) LOOP
        ch := substr(source, i, 1);
        codepoint := ascii(ch);
        IF codepoint BETWEEN 48 AND 57
            OR codepoint BETWEEN 97 AND 122
            OR ch = '_' THEN
            ascii_token := ascii_token || ch;
            previous_cjk := '';
            CONTINUE;
        END IF;
        IF ascii_token <> '' THEN
            tokens := array_append(tokens, ascii_token);
            ascii_token := '';
        END IF;
        IF codepoint BETWEEN 13312 AND 40959 THEN
            tokens := array_append(tokens, ch);
            IF previous_cjk <> '' THEN
                tokens := array_append(tokens, previous_cjk || ch);
            END IF;
            previous_cjk := ch;
        ELSE
            previous_cjk := '';
        END IF;
    END LOOP;
    IF ascii_token <> '' THEN
        tokens := array_append(tokens, ascii_token);
    END IF;
    RETURN array_to_string(tokens, ' ');
END;
$$;

CREATE OR REPLACE FUNCTION askbase_search_query(input TEXT)
RETURNS TSQUERY
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
    SELECT to_tsquery(
        'simple',
        regexp_replace(NULLIF(btrim(askbase_search_tokens(input)), ''), '\s+', ' | ', 'g')
    );
$$;

-- ============================================================================
-- 1. 用户表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(64) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_user IS '用户表，邮箱验证码登录，不保存密码';
COMMENT ON COLUMN t_user.id IS '用户 ID，自增主键';
COMMENT ON COLUMN t_user.email IS '登录邮箱，唯一，统一按小写存储';
COMMENT ON COLUMN t_user.nickname IS '显示昵称，默认取邮箱 @ 前一段';
COMMENT ON COLUMN t_user.status IS '用户状态：1=正常，2=禁用';
COMMENT ON COLUMN t_user.created_at IS '创建时间，带时区';
COMMENT ON COLUMN t_user.updated_at IS '更新时间，带时区';

ALTER TABLE t_user ADD CONSTRAINT t_user_email_key UNIQUE (email);

-- ============================================================================
-- 2. 知识库表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    chunk_strategy VARCHAR(32) NOT NULL DEFAULT 'general',
    embed_model VARCHAR(128) NOT NULL DEFAULT '',
    embed_model_id BIGINT,
    vision_model VARCHAR(128) NOT NULL DEFAULT '',
    vision_model_id BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_dataset IS '知识库表，一个用户可建多个知识库';
COMMENT ON COLUMN t_dataset.id IS '知识库 ID，自增主键';
COMMENT ON COLUMN t_dataset.user_id IS '所属用户 ID';
COMMENT ON COLUMN t_dataset.name IS '知识库名称';
COMMENT ON COLUMN t_dataset.description IS '知识库描述';
COMMENT ON COLUMN t_dataset.chunk_strategy IS '知识库解析模板：general/book/paper/resume/qa';
COMMENT ON COLUMN t_dataset.embed_model IS '嵌入模型展示名，创建时从 t_embed_model 拷贝';
COMMENT ON COLUMN t_dataset.embed_model_id IS '绑定的嵌入模型 ID，创建后不可更改';
COMMENT ON COLUMN t_dataset.vision_model IS '视觉模型展示名，可随时更换';
COMMENT ON COLUMN t_dataset.vision_model_id IS '绑定的视觉模型 ID，0 表示未绑定；可随时改，只影响之后的解析';
COMMENT ON COLUMN t_dataset.created_at IS '创建时间，带时区';
COMMENT ON COLUMN t_dataset.updated_at IS '更新时间，带时区';

CREATE INDEX IF NOT EXISTS idx_t_dataset_user_id ON t_dataset (user_id);
CREATE INDEX IF NOT EXISTS idx_t_dataset_embed_model_id ON t_dataset (embed_model_id);
CREATE INDEX IF NOT EXISTS idx_t_dataset_vision_model_id ON t_dataset (vision_model_id);

-- ============================================================================
-- 2b. 用户嵌入模型
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_embed_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    model_id VARCHAR(256) NOT NULL,
    api_url VARCHAR(512) NOT NULL,
    api_key TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_embed_model IS '用户嵌入模型（含 API Key），供知识库绑定';
COMMENT ON COLUMN t_embed_model.user_id IS '所属用户 ID';
COMMENT ON COLUMN t_embed_model.name IS '展示名';
COMMENT ON COLUMN t_embed_model.model_id IS '供应商模型 ID';
COMMENT ON COLUMN t_embed_model.api_url IS 'OpenAI 兼容接口前缀';
COMMENT ON COLUMN t_embed_model.api_key IS 'API Key，明文存储';

CREATE INDEX IF NOT EXISTS idx_t_embed_model_user_id ON t_embed_model (user_id);

-- ============================================================================
-- 2c. 用户视觉模型（官方不种子）
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_vision_model (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    model_id VARCHAR(256) NOT NULL,
    api_url VARCHAR(512) NOT NULL,
    api_key TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_vision_model IS '用户视觉模型（VLM），仅用于给图片原子生成文字描述';
COMMENT ON COLUMN t_vision_model.user_id IS '所属用户 ID';
COMMENT ON COLUMN t_vision_model.name IS '展示名';
COMMENT ON COLUMN t_vision_model.model_id IS '供应商模型 ID';
COMMENT ON COLUMN t_vision_model.api_url IS 'OpenAI 兼容接口前缀';
COMMENT ON COLUMN t_vision_model.api_key IS 'API Key，明文存储';

CREATE INDEX IF NOT EXISTS idx_t_vision_model_user_id ON t_vision_model (user_id);

-- ============================================================================
-- 3. 文档表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL,
    name VARCHAR(512) NOT NULL,
    r2_key VARCHAR(1024) NOT NULL DEFAULT '',
    file_hash VARCHAR(64) NOT NULL DEFAULT '',
    size_bytes BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    progress SMALLINT NOT NULL DEFAULT 0,
    parse_error TEXT,
    parse_version BIGINT NOT NULL DEFAULT 1,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    last_attempt_at TIMESTAMPTZ,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_document IS '文档表，文件经 R2 预签名直传后登记；解析流水线异步执行';
COMMENT ON COLUMN t_document.id IS '文档 ID，自增主键';
COMMENT ON COLUMN t_document.dataset_id IS '所属知识库 ID';
COMMENT ON COLUMN t_document.name IS '文档显示名，默认取原始文件名';
COMMENT ON COLUMN t_document.r2_key IS '对象存储（R2）中的对象 key';
COMMENT ON COLUMN t_document.file_hash IS '文件内容 SHA-256，用于上传去重（幂等登记）';
COMMENT ON COLUMN t_document.size_bytes IS '文件大小，单位字节';
COMMENT ON COLUMN t_document.status IS '状态机：pending→parsing→chunking→embedding→done，失败为 failed';
COMMENT ON COLUMN t_document.progress IS '流水线进度百分比，0-100';
COMMENT ON COLUMN t_document.parse_error IS '失败原因，仅 status=failed 时有值';
COMMENT ON COLUMN t_document.parse_version IS '解析任务版本；重新触发时递增，用于淘汰旧消息';
COMMENT ON COLUMN t_document.attempt_count IS '当前解析版本已执行的业务尝试次数';
COMMENT ON COLUMN t_document.last_error IS '最近一次解析尝试错误，最终失败前也会保留';
COMMENT ON COLUMN t_document.last_attempt_at IS '最近一次解析尝试时间';
COMMENT ON COLUMN t_document.enabled IS '是否启用；停用后其分块不参与检索';
COMMENT ON COLUMN t_document.created_at IS '创建时间，带时区';
COMMENT ON COLUMN t_document.updated_at IS '更新时间，带时区';

CREATE INDEX IF NOT EXISTS idx_t_document_dataset_id ON t_document (dataset_id);
-- 上传幂等：同一知识库内相同文件 hash 只登记一次
CREATE UNIQUE INDEX IF NOT EXISTS idx_t_document_dataset_hash ON t_document (dataset_id, file_hash) WHERE file_hash <> '';

-- ============================================================================
-- 4. 事务 Outbox
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic VARCHAR(128) NOT NULL,
    aggregate_id BIGINT NOT NULL,
    payload JSONB NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    publish_attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_outbox IS '事务消息表；relay 可靠发布到 RabbitMQ 后标记 published';
COMMENT ON COLUMN t_outbox.topic IS '消息主题';
COMMENT ON COLUMN t_outbox.aggregate_id IS '关联业务实体 ID';
COMMENT ON COLUMN t_outbox.payload IS '待发布 JSON 消息体';
COMMENT ON COLUMN t_outbox.status IS '发布状态：pending 或 published';
COMMENT ON COLUMN t_outbox.publish_attempts IS '发布尝试次数';
COMMENT ON COLUMN t_outbox.next_attempt_at IS '下次允许发布时间';
COMMENT ON COLUMN t_outbox.published_at IS 'RabbitMQ publisher confirm 成功时间';
COMMENT ON COLUMN t_outbox.last_error IS '最近一次发布错误';

CREATE INDEX IF NOT EXISTS idx_t_outbox_pending ON t_outbox (next_attempt_at, id) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_t_outbox_published_at ON t_outbox (published_at) WHERE status = 'published';

-- ============================================================================
-- 5. 分块表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    chunk_index INT NOT NULL DEFAULT 0,
    content TEXT NOT NULL,
    token_num INT NOT NULL DEFAULT 0,
    image_key TEXT NOT NULL DEFAULT '',
    element_type VARCHAR(32) NOT NULL DEFAULT 'text',
    page_number INTEGER NOT NULL DEFAULT 0,
    bbox JSONB NOT NULL DEFAULT '[]'::jsonb,
    parser_name VARCHAR(64) NOT NULL DEFAULT '',
    search_vector TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', askbase_search_tokens(content))) STORED,
    q_1024_vec vector(1024),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_chunk IS '文档分块表，向量化后参与检索';
COMMENT ON COLUMN t_chunk.id IS '分块 ID，自增主键';
COMMENT ON COLUMN t_chunk.document_id IS '所属文档 ID';
COMMENT ON COLUMN t_chunk.dataset_id IS '冗余知识库 ID，检索时免 join 文档表';
COMMENT ON COLUMN t_chunk.chunk_index IS '块在文档内的序号，从 0 开始';
COMMENT ON COLUMN t_chunk.content IS '分块文本内容';
COMMENT ON COLUMN t_chunk.image_key IS '图片原子在对象存储中的 key，空表示纯文本块';
COMMENT ON COLUMN t_chunk.element_type IS '来源元素类型：text/title/table/formula/image/chart/code/list';
COMMENT ON COLUMN t_chunk.page_number IS '元素所在 PDF 页码，从 1 开始；0 表示未知或非分页文档';
COMMENT ON COLUMN t_chunk.bbox IS '元素在页面内的坐标框，由解析器原样返回';
COMMENT ON COLUMN t_chunk.parser_name IS '产生该分块的解析器及模型版本';
COMMENT ON COLUMN t_chunk.search_vector IS '中英文全文检索向量：英文单词、中文单字与相邻双字词元';
COMMENT ON COLUMN t_chunk.token_num IS '分块 token 估算数（按 rune 估算）';
COMMENT ON COLUMN t_chunk.q_1024_vec IS '1024 维嵌入；其它维度按 q_N_vec 动态加列';
COMMENT ON COLUMN t_chunk.enabled IS '是否启用；禁用后不参与检索';
COMMENT ON COLUMN t_chunk.created_at IS '创建时间，带时区';
COMMENT ON COLUMN t_chunk.updated_at IS '更新时间，带时区';

CREATE INDEX IF NOT EXISTS idx_t_chunk_document_id ON t_chunk (document_id);
CREATE INDEX IF NOT EXISTS idx_t_chunk_dataset_id ON t_chunk (dataset_id);
-- 向量近邻索引（余弦）；数据量小也能建，pgvector 自动退化为精确检索
CREATE INDEX IF NOT EXISTS idx_t_chunk_q_1024_vec_hnsw ON t_chunk USING hnsw (q_1024_vec vector_cosine_ops);
CREATE INDEX IF NOT EXISTS idx_t_chunk_search_vector_gin ON t_chunk USING gin (search_vector);

-- ============================================================================
-- 6. 会话表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    dataset_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_session IS '对话会话表，一个会话绑定一个知识库';
COMMENT ON COLUMN t_session.id IS '会话 ID，自增主键';
COMMENT ON COLUMN t_session.user_id IS '所属用户 ID';
COMMENT ON COLUMN t_session.dataset_id IS '绑定知识库 ID';
COMMENT ON COLUMN t_session.title IS '会话标题，默认取首条问题截断';
COMMENT ON COLUMN t_session.status IS '会话状态：1=进行中，2=已归档';
COMMENT ON COLUMN t_session.created_at IS '创建时间，带时区';
COMMENT ON COLUMN t_session.updated_at IS '更新时间，带时区';

CREATE INDEX IF NOT EXISTS idx_t_session_user_id ON t_session (user_id);
CREATE INDEX IF NOT EXISTS idx_t_session_user_status ON t_session (user_id, status);

-- ============================================================================
-- 7. 消息表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_message IS '对话消息表';
COMMENT ON COLUMN t_message.id IS '消息 ID，自增主键';
COMMENT ON COLUMN t_message.session_id IS '所属会话 ID';
COMMENT ON COLUMN t_message.role IS '角色：user / assistant';
COMMENT ON COLUMN t_message.content IS '消息文本内容';
COMMENT ON COLUMN t_message.created_at IS '创建时间，带时区';

CREATE INDEX IF NOT EXISTS idx_t_message_session_id ON t_message (session_id);

-- 消息引用独立保存检索时分数，历史消息无需重新检索即可还原引用元数据。
CREATE TABLE IF NOT EXISTS t_message_citation (
    message_id BIGINT NOT NULL,
    position INTEGER NOT NULL CHECK (position > 0),
    chunk_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (message_id, position)
);

COMMENT ON TABLE t_message_citation IS '助手消息引用的分块及检索时元数据';
COMMENT ON COLUMN t_message_citation.message_id IS '所属助手消息 ID';
COMMENT ON COLUMN t_message_citation.position IS '引用编号，对应回答中的 [n]';
COMMENT ON COLUMN t_message_citation.chunk_id IS '引用的 t_chunk ID';
COMMENT ON COLUMN t_message_citation.score IS '生成回答时的检索分数';

CREATE INDEX IF NOT EXISTS idx_t_message_citation_chunk_id ON t_message_citation (chunk_id);
